# Generated by Django 3.2.6 on 2021-08-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0002_auto_20210823_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='categoria',
        ),
        migrations.AddField(
            model_name='dvd',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias', to='dvd.Categoria'),
        ),
    ]
