# Generated by Django 3.2.6 on 2021-09-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0004_dvd_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='estado2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='cant_unidades',
            field=models.IntegerField(verbose_name='Cantidad de unidades'),
        ),
    ]
