# Generated by Django 3.2.6 on 2021-08-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amigo',
            table='amigos',
        ),
    ]
